### ISSUE TITLE
Disable Opera's message "Click to activate and use this control"

### ISSUE THREAD

**Issue by fat32** [PrestoXen/openopera-issues#12]
https://www.youtube.com/watch?v=ToieM0c1YxY

**Comment by Zero3K** [comment]
A user by the nickname of som1 in the IRC channel has made a patch to do exactly that. You can find it at http://paste.fedoraproject.org/531393/49176771/.

**Comment by Zero3K** [comment]
I'll go ahead and close this issue since a patch has been made.
